#!/usr/bin/env sh
echo starting...

if [ ${VIRTUAL_ENV}empty != empty ]
then
	echo This command is meant to be run outside any venv
	echo and expects an installed venv at $HOME/venv.
	echo Aborting.
	exit 100
fi

$HOME/venv/bin/python3 scripts/server.py

