#!/usr/bin/env bash

if [ ${VIRTUAL_ENV}empty != empty ]
then
	echo This command is meant to be run outside any venv
	echo and expects an installed venv at $HOME/venv.
	echo Aborting.
	exit 100
fi

source venv/bin/activate
echo starting...
python3 scripts/run-server.py

